name: kgk
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+98

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # For State Management
  flutter_bloc: ^9.1.1

  # For API
  dartz: ^0.10.1
  http: ^1.4.0

  # For Device Info
  device_info_plus: ^11.5.0

  # For Connectivity
  connectivity_plus: ^6.1.4

  # For Local Storage
  hive: ^2.2.3

  # For Path Provider for File Path
  path_provider: ^2.1.5

  equatable: ^2.0.7

  # For Snackbar Message
  toastification: ^3.0.3

  # For SVG Image File
  flutter_svg: ^2.2.0

  # For Cached Network Image
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  google_places_flutter: ^2.1.0

  # For Country Code Picker
  #  country_picker: ^2.0.27
  country_picker:
    git:
      url: https://gitlab.bytestechnolab.com/flutter/flutter_country_picker.git
      ref: main
    # path: ../country_picker

  # For Carousel image Slider
  carousel_slider: ^5.1.1

  # For Rating Bar
  flutter_rating_bar: ^4.0.1

  #For Read more / Read less Text
  readmore: ^3.0.0

  #For Screen Util
  flutter_screenutil: ^5.9.3

  #For Dotted Border
  dotted_border: ^3.1.0

  #For Image Pick
  image_picker: ^1.1.2

  #For Permission Handle
  permission_handler: ^12.0.0+1

  #For Date Time Conversion
  intl: ^0.20.2

  #For Qr Code Scanner
  mobile_scanner: ^7.0.1

  #For Webview
  webview_flutter: ^4.13.0

  #For Google Map
  google_maps_flutter: ^2.12.3

  #For Range Sliders
  syncfusion_flutter_sliders: ^30.1.38

  #For Calendar
  syncfusion_flutter_calendar: ^30.1.38

  syncfusion_flutter_charts: ^30.1.38

  #For QR Code
  qr_flutter: ^4.1.0

  #For Share
  share_plus: ^11.0.0

  #For Bounce animation
  flutter_bounceable: ^1.2.0

  #For Video Player
  video_player: ^2.10.0

  html: ^0.15.6

  # mime_type and http_parser both Used in Multipart File Uploading in ApiService class
  mime_type: ^1.0.1

  http_parser: ^4.1.2

  # access location
  geolocator: ^14.0.2

  # For Url Launcher
  url_launcher: ^6.3.1

  # For Deep Linking
  flutter_branch_sdk: ^8.5.0

  country_phone_validator: ^1.0.1

  # For Photo View
  photo_view: ^0.15.0
  model_viewer_plus: ^1.9.3

  firebase_core: ^3.15.0
  firebase_crashlytics: ^4.3.8

  flutter_langdetect: ^0.0.2
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/locales/
    - shorebird.yaml

  fonts:
    - family: EBGaramond
      fonts:
        - asset: assets/fonts/EB_Garamond/EBGaramond-Regular.ttf

    - family: EBGaramondMedium
      fonts:
        - asset: assets/fonts/EB_Garamond/EBGaramond-Medium.ttf

    - family: EBGaramondSemiBold
      fonts:
        - asset: assets/fonts/EB_Garamond/EBGaramond-SemiBold.ttf

    - family: EBGaramondBold
      fonts:
        - asset: assets/fonts/EB_Garamond/EBGaramond-Bold.ttf

    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf

    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter/Inter-Medium.ttf

    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf

    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter/Inter-Bold.ttf
