sonar.projectKey=KGK
sonar.projectName=KGK
sonar.projectVersion=1.0
sonar.sources=lib
sonar.language=flutter
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart,**/*.config.dart
sonar.token=sqp_560772e410346cb4e951a4732e2b137dc6c5ca5e
sonar.host.url=http://localhost:9000
