import 'package:kgk/kgk.dart';

class BlocGenerator {
  static List<BlocProvider> generateBlocList(BuildContext context) {
    return [
      BlocProvider<GetReadyBloc>(create: (_) => GetReadyBloc()),
      BlocProvider<AppBloc>(create: (_) => AppBloc()..add(LoadAppEvent(context: context)), lazy: false),
      BlocProvider<CategoriesBloc>(create: (_) => CategoriesBloc()),
      BlocProvider<HomeBloc>(create: (_) => HomeBloc()),
      BlocProvider<CategoriesBloc>(create: (_) => CategoriesBloc()),
      BlocProvider<MyBagBloc>(create: (_) => MyBagBloc()),
      BlocProvider<SupportBloc>(create: (_) => SupportBloc()),
      BlocProvider<CompanyBloc>(create: (_) => CompanyBloc()),
      BlocProvider<ProfileBloc>(create: (_) => ProfileBloc()),
      BlocProvider<LandingBloc>(create: (_) => LandingBloc()),
      BlocProvider<ForgotPasswordBloc>(create: (_) => ForgotPasswordBloc()),
      BlocProvider<ResetPasswordBloc>(create: (_) => ResetPasswordBloc()),
      BlocProvider<ForgotEmailSentBloc>(create: (_) => ForgotEmailSentBloc()),
      BlocProvider<SortFilterBloc>(create: (_) => SortFilterBloc()),
      BlocProvider<StoneListingBloc>(create: (_) => StoneListingBloc()),
      BlocProvider<CompareProductBloc>(create: (_) => CompareProductBloc()),
      BlocProvider<PaymentBloc>(create: (_) => PaymentBloc()),
      BlocProvider<SearchBloc>(create: (_) => SearchBloc()),
      BlocProvider<NotificationSettingsBloc>(create: (_) => NotificationSettingsBloc()),
      BlocProvider<FaqBloc>(create: (_) => FaqBloc()),
      BlocProvider<PreferencesBloc>(create: (_) => PreferencesBloc()),
      BlocProvider<MakeInquiryBloc>(create: (_) => MakeInquiryBloc()),
      BlocProvider<DashboardBloc>(create: (_) => DashboardBloc()),
      BlocProvider<PddListingBloc>(create: (_) => PddListingBloc()),
      BlocProvider<ConceptListBloc>(create: (_) => ConceptListBloc()),
      BlocProvider<ProjectListingBloc>(create: (_) => ProjectListingBloc()),
      BlocProvider<DesignBriefsBloc>(create: (_) => DesignBriefsBloc()),
      BlocProvider<DesignListingBloc>(create: (_) => DesignListingBloc()),
      BlocProvider<MonitoringBloc>(create: (_) => MonitoringBloc()),
      BlocProvider<EditWatchlistBloc>(create: (_) => EditWatchlistBloc()),
      BlocProvider<DesignLibraryFeedbackBloc>(create: (_) => DesignLibraryFeedbackBloc()),
      BlocProvider<StonesLandingBloc>(create: (_) => StonesLandingBloc()),
      BlocProvider<WatchlistBloc>(create: (_) => WatchlistBloc()),
      BlocProvider<DesignLibraryBloc>(create: (_) => DesignLibraryBloc()),
      BlocProvider<ActivityLogBloc>(create: (_) => ActivityLogBloc()),
      BlocProvider<AddToWatchlistBloc>(create: (_) => AddToWatchlistBloc()),
      BlocProvider<ManufacturerOrderListingBloc>(create: (_) => ManufacturerOrderListingBloc()),
      BlocProvider<RetailerOrderListingBloc>(create: (_) => RetailerOrderListingBloc()),
      BlocProvider<OrionBloc>(create: (_) => OrionBloc()),
      BlocProvider<NewsletterBloc>(create: (_) => NewsletterBloc()),
      BlocProvider<WishlistUpdaterServiceBloc>(create: (_) => WishlistUpdaterServiceBloc(), lazy: false),
      BlocProvider<AdvanceSortFilterBloc>(create: (_) => AdvanceSortFilterBloc()),
      BlocProvider<MyInquiryBloc>(create: (_) => MyInquiryBloc()),
    ];
  }
}
