import 'package:kgk/kgk.dart';

class BlocGenerator {
  static List<BlocProvider> generateBlocList() {
    return [
      BlocProvider<SignInBloc>(create: (_) => SignInBloc()),
      BlocProvider<GetReadyBloc>(create: (_) => GetReadyBloc()),
      BlocProvider<AppBloc>(create: (_) => AppBloc()..add(LoadAppEvent()), lazy: false),
      BlocProvider<SignInBloc>(create: (_) => SignInBloc()),
      BlocProvider<SignUpBloc>(create: (_) => SignUpBloc()),
      BlocProvider<CategoriesBloc>(create: (_) => CategoriesBloc()),
      BlocProvider<HomeBloc>(create: (_) => HomeBloc()),
      BlocProvider<CategoriesBloc>(create: (_) => CategoriesBloc()),
      BlocProvider<MyBagBloc>(create: (_) => MyBagBloc()),
      BlocProvider<SupportBloc>(create: (_) => SupportBloc()),
      BlocProvider<CompanyBloc>(create: (_) => CompanyBloc()),
      BlocProvider<ProfileBloc>(create: (_) => ProfileBloc()),
      BlocProvider<LandingBloc>(create: (_) => LandingBloc()),
      BlocProvider<ForgotPasswordBloc>(create: (_) => ForgotPasswordBloc()),
      BlocProvider<ResetPasswordBloc>(create: (_) => ResetPasswordBloc()),
      BlocProvider<ForgotEmailSentBloc>(create: (_) => ForgotEmailSentBloc()),
      BlocProvider<CollectionBloc>(create: (_) => CollectionBloc()),
      BlocProvider<SortFilterBloc>(create: (_) => SortFilterBloc()),
      BlocProvider<SettingDetailBloc>(create: (_) => SettingDetailBloc()),
      BlocProvider<StoneListingBloc>(create: (_) => StoneListingBloc()),
      BlocProvider<CompleteProductBloc>(create: (_) => CompleteProductBloc()),
      BlocProvider<CompareProductBloc>(create: (_) => CompareProductBloc()),
      BlocProvider<AddAddressBloc>(create: (_) => AddAddressBloc()),
      BlocProvider<WishlistBloc>(create: (_) => WishlistBloc()),
      BlocProvider<PaymentBloc>(create: (_) => PaymentBloc()),
      BlocProvider<WriteReviewBloc>(create: (_) => WriteReviewBloc()),
      BlocProvider<AddressListBloc>(create: (_) => AddressListBloc()),
      BlocProvider<DiamondInfoPopupBloc>(create: (_) => DiamondInfoPopupBloc()),
      BlocProvider<DiamondFilterBloc>(create: (_) => DiamondFilterBloc()..add(const LoadDiamondFilterDataEvent())),
      BlocProvider<AuctionBloc>(create: (_) => AuctionBloc()),
      BlocProvider<OrdersBloc>(create: (_) => OrdersBloc()),
      BlocProvider<AuctionListingBloc>(create: (_) => AuctionListingBloc()),
      BlocProvider<SearchBloc>(create: (_) => SearchBloc()),
      BlocProvider<NotificationSettingsBloc>(create: (_) => NotificationSettingsBloc()),
      BlocProvider<FaqBloc>(create: (_) => FaqBloc()),
      BlocProvider<PreferencesBloc>(create: (_) => PreferencesBloc()),
      BlocProvider<MakeInquiryBloc>(create: (_) => MakeInquiryBloc()),
      BlocProvider<ContactUsBloc>(create: (_) => ContactUsBloc()),
      BlocProvider<DashboardBloc>(create: (_) => DashboardBloc()),
      BlocProvider<PddListingBloc>(create: (_) => PddListingBloc()),
      BlocProvider<ConceptListBloc>(create: (_) => ConceptListBloc()),
      BlocProvider<SavedAddressBloc>(create: (_) => SavedAddressBloc()),
      BlocProvider<ShippingAddressBloc>(create: (_) => ShippingAddressBloc()),
      BlocProvider<ProjectListingBloc>(create: (_) => ProjectListingBloc()),
      BlocProvider<DesignBriefsBloc>(create: (_) => DesignBriefsBloc()),
      BlocProvider<DesignListingBloc>(create: (_) => DesignListingBloc()),
      BlocProvider<StylesListingBloc>(create: (_) => StylesListingBloc()),
      BlocProvider<DigitalCatalogueBloc>(create: (_) => DigitalCatalogueBloc()),
      BlocProvider<MonitoringBloc>(create: (_) => MonitoringBloc()),
      BlocProvider<FindStoreBloc>(create: (_) => FindStoreBloc()),
      BlocProvider<CadLibraryListingBloc>(create: (_) => CadLibraryListingBloc()),
      BlocProvider<ExhibitionDetailsOrdersBloc>(create: (_) => ExhibitionDetailsOrdersBloc()),
      BlocProvider<EditWatchlistBloc>(create: (_) => EditWatchlistBloc()),
      BlocProvider<DesignLibraryFeedbackBloc>(create: (_) => DesignLibraryFeedbackBloc()),
      BlocProvider<ExhibitionListingBloc>(create: (_) => ExhibitionListingBloc()),
      BlocProvider<AllReviewBloc>(create: (_) => AllReviewBloc()),
      BlocProvider<StonesLandingBloc>(create: (_) => StonesLandingBloc()),
      BlocProvider<WatchlistBloc>(create: (_) => WatchlistBloc()),
      BlocProvider<ProductListBloc>(create: (_) => ProductListBloc()),
      BlocProvider<DesignLibraryBloc>(create: (_) => DesignLibraryBloc()),
      BlocProvider<ManufacturerOrderListingBloc>(create: (_) => ManufacturerOrderListingBloc()),
    ];
  }
}
