import 'package:kgk/kgk.dart';

class BlocGenerator {
  static List<BlocProvider> generateBlocList() {
    return [
      BlocProvider<SignInBloc>(create: (_) => SignInBloc()),
      BlocProvider<GetReadyBloc>(create: (_) => GetReadyBloc()),
      BlocProvider<AppBloc>(create: (_) => AppBloc()..add(LoadAppEvent()), lazy: false),
      BlocProvider<SignInBloc>(create: (_) => SignInBloc()),
      BlocProvider<SignUpBloc>(create: (_) => SignUpBloc()),
      BlocProvider<CategoriesBloc>(create: (_) => CategoriesBloc()),
      BlocProvider<HomeBloc>(create: (_) => HomeBloc()),
      BlocProvider<CategoriesBloc>(create: (_) => CategoriesBloc()),
      BlocProvider<MyBagBloc>(create: (_) => MyBagBloc()),
      BlocProvider<SupportBloc>(create: (_) => SupportBloc()),
      BlocProvider<ProfileBloc>(create: (_) => ProfileBloc()),
      BlocProvider<DashboardBloc>(create: (_) => DashboardBloc()),
      BlocProvider<ForgotPasswordBloc>(create: (_) => ForgotPasswordBloc()),
      BlocProvider<ResetPasswordBloc>(create: (_) => ResetPasswordBloc()),
      BlocProvider<ForgotEmailSentBloc>(create: (_) => ForgotEmailSentBloc()),
      BlocProvider<CollectionBloc>(create: (_) => CollectionBloc()),
      BlocProvider<ProductListBloc>(create: (_) => ProductListBloc()),
      BlocProvider<SortFilterBloc>(create: (_) => SortFilterBloc()),
      BlocProvider<SettingDetailBloc>(create: (_) => SettingDetailBloc()),
      BlocProvider<StoneDetailBloc>(create: (_) => StoneDetailBloc()),
      BlocProvider<StoneListingBloc>(create: (_) => StoneListingBloc()),
      BlocProvider<SettingListingBloc>(create: (_) => SettingListingBloc()),
      BlocProvider<CompleteProductBloc>(create: (_) => CompleteProductBloc()),
      BlocProvider<CompareProductBloc>(create: (_) => CompareProductBloc()),
      BlocProvider<AddAddressBloc>(create: (_) => AddAddressBloc()),
      BlocProvider<WishlistBloc>(create: (_) => WishlistBloc()),
      BlocProvider<PaymentBloc>(create: (_) => PaymentBloc()),
      BlocProvider<WriteReviewBloc>(create: (_) => WriteReviewBloc()),
      BlocProvider<AddressListBloc>(create: (_) => AddressListBloc()),
      BlocProvider<DiamondInfoPopupBloc>(create: (_) => DiamondInfoPopupBloc()),
      BlocProvider<DiamondFilterBloc>(create: (_) => DiamondFilterBloc()),
      BlocProvider<AuctionBloc>(create: (_) => AuctionBloc()),
      BlocProvider<OrdersBloc>(create: (_) => OrdersBloc()),
      BlocProvider<OrderDetailBloc>(create: (_) => OrderDetailBloc()),
      BlocProvider<AuctionListingBloc>(create: (_) => AuctionListingBloc()),
      BlocProvider<SearchBloc>(create: (_) => SearchBloc()),
      BlocProvider<SearchResultBloc>(create: (_) => SearchResultBloc()),
    ];
  }
}
